sprofileportal/urls.py
from django.conf.urls import url
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from student import views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^studentportal/', include('student.urls')),
    url(r'students/$', views.StudentList.as_view()),
    url(r'^students/(?P<pk>[0-9]+)$', views.StudentDetail.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)
    

student/urls.py
from django.conf.urls import url

from django.contrib.auth import views as auth_views
from . import views

app_name = 'student'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', auth_views.login, {'template_name': 'student/login.html'}, name='login'),
     url(r'^logout/$', views.logout_view, name='logout'),
     url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^ranks/$', views.RanksView.as_view(), name='ranks'),
     #url(r'^studentcreate/$', views.StudentCreate.as_view(), name='studentcreate'),
     url(r'^register/studentcreate/$', views.StudentFormView.as_view(), name='studentcreate'),
    url(r'^register/studentupdate/$', views.UpdateStudentFormView.as_view(), name='studentupdate'),
    url(r'^register/studentsite/$', views.StudentSiteFormView.as_view(), name='studentsite'),
    # /music/<album_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    
    #url(r'^student/(?P<pk>[0-9]+)/$', views.StudentUpdate.as_view(), name='album-update'),
    
]

student/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver

class Student(models.Model):
    user = models.ForeignKey(User,default=None,null=True)
    enrollment_no = models.CharField(max_length=50, default=None, unique=True)
    first_name = models.CharField(max_length=200, default=None)
    last_name = models.CharField(max_length=200, default=None)
    email = models.EmailField(default=None,null=True)
    current_semester = models.IntegerField(default=1, null=True)
    graduation_year = models.IntegerField(null=True)
    is_active = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    image = models.FileField(blank=True, null=True)


class Site(models.Model):
    site_name = models.CharField(max_length=200, default=None)
    site_type = models.CharField(max_length=100, default=None)
    site_active = models.BooleanField(default=False)
    site_count = models.IntegerField(default=0)

    def __str__(self):
        return self.site_name

class StudentSite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=None,null=True)
    site = models.ForeignKey(Site, on_delete=models.CASCADE,default=None,null=True)
    username = models.CharField(max_length=200, default=None,null=True)
    site_rank = models.IntegerField(default=None,null=True)
    site_rating = models.IntegerField(default=None,null=True)
    site_point = models.FloatField(default=None,null=True)
    site_ques_solved = models.IntegerField(default=None,null=True)
    site_repo = models.IntegerField(default=None,null=True)
    site_star = models.IntegerField(default=None,null=True)
    site_contribution = models.IntegerField(default=None,null=True)
    site_follower = models.IntegerField(default=None,null=True)
    site_following = models.IntegerField(default=None,null=True)
    is_active = models.BooleanField(default=False)
    no_of_sites = models.IntegerField(default=None,null=True)

student/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Student, StudentSite, Site

class UserForm(forms.ModelForm):   
    class Meta:
        model = User
        fields = ['username','email','password']

class StudentForm(forms.ModelForm):   
    class Meta:
        model = Student
        fields = ['enrollment_no','first_name','last_name','current_semester','graduation_year','image']
        

class StudentSiteForm(forms.ModelForm):   
    class Meta:
        model = StudentSite
        fields = ['site','username','is_active']

student/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Student, StudentSite
from .serializers import StudentSerializer
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm,StudentForm, StudentSiteForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
import requests
import bs4 as bs
import urllib.request
from bs4 import BeautifulSoup

def codechef(username):
    head = "https://wwww.codechef.com/users/"
    URL = head + username

    page  = requests.get(URL)
    soup = BeautifulSoup(page.content,'html.parser')

    #These three lines give the Rating of the user.
    listRating = list(soup.findAll('div',class_="rating-number"))
    rating = list(listRating[0].children)
    rating = rating[0]
    out = str(rating)
    #print ("Rating: "+rating)

    listGCR = []  #Global and country ranking.
    listRanking = list(soup.findAll('div',class_="rating-ranks"))
    rankingSoup = listRanking[0] 
    for item in rankingSoup.findAll('a'):
            listGCR.append(item.get_text()) #Extracting the text from all anchor tags
    #print ("Global Ranking: "+listGCR[0])
    #print ("Country Ranking: "+listGCR[1])
    out = out + " " + str(listGCR[0])
    return out

def spoj(username):
    base = "https://spoj.com/users/"
    var = username
    url = base + var
    sauce = requests.get(url) 
    soup = BeautifulSoup(sauce.content,'lxml')     # lxml is a parser
    #print(soup.prettify())
    iList = []
    info = (soup.find_all('p'))
    for i in info:
        iList.append(i.text)

    #print (iList[2]) #World rank
    #print (iList[3]) #Institution
    no_of_questions = int(soup.find('dd').text)
    #print(" no. of questions = ",no_of_questions)
    s = str(iList[2].lstrip())+" "+str(no_of_questions)
    return s

def github(username):
    url = "https://github.com/"+username
    sauce = urllib.request.urlopen(url).read()    
    soup = bs.BeautifulSoup(sauce,'lxml')     # lxml is a parser
    #print(soup)

    things = soup.find_all('span',class_='Counter')
    repoNo = int(things[0].text)
    starsNo = int(things[1].text)
    FollowersNo = int(things[2].text)
    FollowingNo = int(things[3].text)

    contribution = (soup.find('h2',class_='f4 text-normal mb-2').text).lstrip().split(" ")
    no_contribution = int(contribution[0])
    #print (no_contribution)
    s = str(repoNo)+" "+str(starsNo)+" "+str(FollowersNo)+" "+str(FollowingNo)+" "+str(no_contribution)
    return (s)

def codebuddy(username):
    URL = "https://codebuddy.co.in/ranks/practice"
    page  = requests.get(URL)
    soup = BeautifulSoup(page.content,'html.parser')
    table = list(soup.find_all('tr'))
    for i in table:
        parameters = list(i.find_all('label'))
        #print (i.find('label',class_="highlight").text)
        if str(parameters[1].text)==username:
            output = str(int(parameters[0].text))+" "+str(int(parameters[2].text))+" "+str(float(parameters[3].text))
            return (output)
    return (-1)


#students/
class StudentList(APIView):

    def get(self,request):
        students = Student.objects.all()
        serializer = StudentSerializer(students, many=True)
        return Response(serializer.data)

    def post(self,request):
        serializer = StudentSerializer(data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        
        

class StudentDetail(APIView):

    def get(self,request,pk):
        try:
            student = Student.objects.get(pk=pk)
        except Student.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        
        student = Student.objects.get(pk=pk)
        serializer = StudentSerializer(student)
        return Response(serializer.data)

    def put(self,request,pk):
        try:
            student = Student.objects.get(pk=pk)
        except Student.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        
        student = Student.objects.get(pk=pk)
        serializer = StudentSerializer(student, data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class IndexView(generic.ListView):
    template_name = 'student/index.html'

    def get_queryset(self):
        return Student.objects.filter().order_by('enrollment_no')

class DetailView(generic.DetailView):
    model = Student
    template_name = 'student/detail.html'

class AlbumCreate(CreateView):
    model = Student
    

class StudentUpdate(UpdateView):
    model = Student
    fields = ['first_name','last_name','current_semester','graduation_year']
    success_url = reverse_lazy('student:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'student/registration_form.html'

    #display a blank form
    def get(self, request):
        if not request.user.is_authenticated():
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form})
        else:
            return redirect('student:index')
    #process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User object if credentials are correct
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('http://127.0.0.1:8000/studentportal/register/studentcreate/')

        return render(request, self.template_name, {'form': form})

class StudentCreate(CreateView):
    model = Student
    fields = '__all__'
    success_url = reverse_lazy('student:index')

class StudentFormView(View):
    
    form_class = StudentForm
    template_name = 'student/registration_form.html'
        
    def get(self, request):
        if request.user.is_authenticated():
            my_record = Student.objects.filter(id=request.user.id).count()
            if my_record!=0:
                return redirect('student:index')
            else:
                form = self.form_class(None)
                return render(request, self.template_name, {'form': form})
        else:
            return redirect('student:index')

    def post(self, request):
        form = self.form_class(request.POST)
        
        if form.is_valid():
            count = Student.objects.filter(user=request.user).count()
            if count==0:
                student = form.save(commit=False)
                student.user = request.user
                student.is_active = True
                student.id = request.user.id
                student.save()
                return redirect('student:index')
            else:
                return render(request, self.template_name, {'form': form})

        return render(request, self.template_name, {'form': form})

class UpdateStudentFormView(View):
    
    form_class = StudentForm
    template_name = 'student/registration_form.html'
        
    def get(self, request):
        if request.user.is_authenticated():
            my_record = Student.objects.get(id=request.user.id)
            form = self.form_class(instance=my_record)
            return render(request, self.template_name, {'form': form})
        else:
            return redirect('student:index')

    def post(self, request):
        my_record = Student.objects.get(id=request.user.id)
        form = self.form_class(request.POST,instance=my_record)
        
        if form.is_valid():
            student = form
            student.save()
            return redirect('student:index')
        else:
            return render(request, self.template_name, {'form': form})

        return render(request, self.template_name, {'form': form})

class StudentSiteFormView(View):
    
    form_class = StudentSiteForm
    template_name = 'student/registration_form.html'
        
    def get(self, request):
        if request.user.is_authenticated():
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form})
        else:
            return redirect('student:index')

    def post(self, request):
        form = self.form_class(request.POST)
        
        if form.is_valid():
            studentsite = form.save(commit=False)
            studentsite.user = request.user
            studentsite.is_active = True
            site1 = str(form.cleaned_data.get('site'))
            if site1 == 'codechef':
                out = codechef(form.cleaned_data['username']).split(" ")
                studentsite.site_rating = int(out[0])
                studentsite.site_rank = int(out[1])
            if site1 == 'spoj':
                out = spoj(form.cleaned_data['username']).split(" ")
                studentsite.site_rank = int(out[2].lstrip('#'))
                studentsite.site_point = float(out[3].lstrip('('))
                studentsite.site_ques_solved = int(out[5])
            if site1 == 'github':

student/templates/student/base.html
<html>
<head>
	<title>{% block title %}Student Profile Portal{% endblock %}</title>
	{% load staticfiles %}

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
	<link rel="stylesheet" type="text/css" href="{% static 'student/style.css' %}" />

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
			 <span class="icon-bar"></span>
			 <span class="icon-bar"></span>
			 <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="{% url 'student:index' %}">Portal</a>
	</div>
	
    <!-- items -->
	<div class="collapse navbar-collapse" id="topNavBar">
		
		<ul class="nav navbar-nav">
			<li class="active">
				<a href="{% url 'student:index' %}">	
					<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
					Students
				</a>
			</li>
			
		</ul>

		<form class="navbar-form navbar-left" role="search" method="get" action="#">
			<div class="form-group">
				<input type="text" class="form-control" name="q" value="">
			</div>
			<button type="submit" class="btn btn-default">Search</button>
		
		</form>

		<ul class="nav navbar-nav navbar-right">
			{% if request.user.is_authenticated %}
			<li class="">
				<a href="{% url 'student:ranks' %}">	
					<span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp;
					Ranking
				</a>
			</li>
                        <li class="">
				<a href="{% url 'student:studentupdate' %}">	
					<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
					Update details
				</a>
			</li>
			<li class="">
				<a href="{% url 'student:studentcreate' %}">	
					<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
					Add details
				</a>
			</li>
			
                        
			<li class="">
				<a href="{% url 'student:logout' %}">	
					<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
					Logout
				</a>
			</li>
			
                        {% else %}
                         <li class="">
				<a href="{% url 'student:register' %}">	
					<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
					Register
				</a>
			</li>
			
                        
			<li class="">
				<a href="{% url 'student:login' %}">	
					<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
					Login
				</a>
			</li>
                        {% endif %}
		</ul>

	</div>
    </div>
</nav>
<h3>user = {{request.user.username}}</h3>
{% block body %}
{% endblock %}

</body>
</html>

student/templates/student/detail - Copy.html
{% extends 'student/base.html' %}
{% block title %}Details page{% endblock %}
{% block body %}



<h1>{{student.enrollment_no}}</h1>
<h3>{{student.first_name}}</h3>
<h3>{{student.user}}</h3>

{% if request.user.id == student.user.id %}
<h3 style="text-align:center;"><a href="{% url 'student:studentsite' %}">Add Site</a></h3>
<br><h2>Sites</h2><hr><br>

	{% for site in student.user.studentsite_set.all %}
                {% if site.site.site_name == "github" %}
		<label for="site{{ forloop.counter}}">
			{{site.site}} -- 
                        {{site.username}}
			
		</label><br>
                {% else %}
                <label for="site{{ forloop.counter}}">
			{{site.site}}
			
		</label><br>
                {% endif %}
	{% endfor %}


{% else %}
<br><h2>Sites</h2><br>

	{% for site in student.user.studentsite_set.all %}
		<label for="site{{ forloop.counter}}">
			{{site.site}}
			
		</label><br>
	{% endfor %}
{% endif %}

{% endblock %}

student/templates/student/detail.html
{% extends 'student/base.html' %}
{% block title %}Details page{% endblock %}
{% block body %}
<div class="conatainer">
		<div class="header">Profile</div>
		<hr id="header_l"><br>
</div>
<div class="row">
<div class="col-lg-2 col-md-3 col-sm-12 col-xs-12">
{% if student.image %}
<img src="{{ student.image.url }}" class="img-responsive">
{% endif %}
<h1>{{student.enrollment_no}}</h1>
<h3>{{student.first_name}}</h3>
<h3>{{student.user}}</h3>

{% if request.user.id == student.user.id %}
<h3><a href="{% url 'student:studentsite' %}">Add Site</a></h3>
{% else %}
<br>
{% endif %}
</div>
<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
<div class="container">
	  <!-- Nav tabs -->
	  <ul class="nav nav-tabs" role="tablist" style="text-transform:uppercase;">
		<li role="presentation" class="active"><a href="#TOPS" aria-controls="TOPS" role="tab" data-toggle="tab">Tops</a></li>
		<li role="presentation"><a href="#GITHUB" aria-controls="GITHUB" role="tab" data-toggle="tab" style="font-size:15px;">GITHUB</a></li>
		<li role="presentation"><a href="#SPOJ" aria-controls="SPOJ" role="tab" data-toggle="tab">SPOJ</a></li>
		<li role="presentation"><a href="#CODECHEF" aria-controls="CODECHEF" role="tab" data-toggle="tab">CODECHEF</a></li>
		<li role="presentation"><a href="#CODEBUDDY" aria-controls="CODEBUDDY" role="tab" data-toggle="tab">CODEBUDDY</a></li>
                <li role="presentation"><a href="#HACKEREARTH" aria-controls="HACKEREARTH" role="tab" data-toggle="tab">HACKEREARTH</a></li>
		
	  </ul>
	  
	<!-- <hr style="width:100%"> -->
	  <br><br>
	  <!-- Tab panes -->
          <font size="5">
	  <div class="tab-content">
		<div role="tabpanel" class="tab-pane fade in active" id="TOPS">
			<div class="content">
				<div class="container">

                                </div>
                        </div>
                </div>
         
          
		<div role="tabpanel" class="tab-pane fade" id="GITHUB">
			<div class="content">
				<div class="container">
				    {% for site in student.user.studentsite_set.all %}
                                    {% if site.site.site_name == "github" %}
                                          <label>Username</label>: {{site.username}}<br>
			                  <label>Repositories</label>: {{site.site_repo}}<br>
                                          <label>Stars</label>: {{site.site_star}}<br>
                                          <label>Contributions</label>: {{site.site_contribution}}<br>
                                          <label>Followers</label>: {{site.site_follower}}<br>
                                          <label>Following</label>: {{site.site_following}}<br>
		                        <br>
                                    {% endif %}
                                    {% endfor %}

                                </div>
                        </div>
                </div>
          
          
		<div role="tabpanel" class="tab-pane fade" id="SPOJ">
			<div class="content">
				<div class="container">
                                    {% for site in student.user.studentsite_set.all %}
                                    {% if site.site.site_name == "spoj" %}
		                        <label>Username</label>: {{site.username}}<br>
			                <label>World Rank</label>: {{site.site_rank}}<br>
                                        <label>Points</label>: {{site.site_point}}<br>
                                        <label>Question Solved</label>: {{site.site_ques_solved}}<br>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                        </div>
                </div>
          
         
		<div role="tabpanel" class="tab-pane fade" id="CODECHEF">
			<div class="content">
				<div class="container">
                                    {% for site in student.user.studentsite_set.all %}
                                    {% if site.site.site_name == "codechef" %}
		                        <label>Username</label>: {{site.username}}<br>
			                <label>World Rank</label>: {{site.site_rank}}<br>
                                        <label>Rating</label>: {{site.site_rating}}<br>
			                <label>Question Solved</label>: {{site.site_ques_solved}}<br>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                        </div>
                </div>
                
                <div role="tabpanel" class="tab-pane fade" id="CODEBUDDY">
			<div class="content">
				<div class="container">
                                    {% for site in student.user.studentsite_set.all %}
                                    {% if site.site.site_name == "codebuddy" %}
		                        <label>Username</label>: {{site.username}}<br>
			                <label>World Rank</label>: {{site.site_rank}}<br>
                                        <label>Points</label>: {{site.site_point}}<br>
			                <label>Question Solved</label>: {{site.site_ques_solved}}<br>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                        </div>
                </div>
                
		<div role="tabpanel" class="tab-pane fade" id="HACKEREARTH">
			<div class="content">
				<div class="container">
                                    {% for site in student.user.studentsite_set.all %}
                                    {% if site.site.site_name == "hackerearth" %}
		                        <label>
			                  {{site.site}} -- 
                                          {{site.username}}
			
		                        </label><br>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                        </div>
                </div>
          </div>
          </font>
</div>
</div>

{% endblock %}

student/templates/student/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

student/templates/student/index.html
{% extends 'student/base.html' %}

{% block body %}
	{% if object_list %}
    	
    	<ul>
		<div class="row">
		    {% for student in object_list %}
			
						<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12"><center>
							<div class="thumbnail" style="height:270px;width:300px;">
								
								<b><a href="{% url 'student:detail' student.id %}" style="text-decoration: none">{{student.enrollment_no}}</a></b><br>
							</div>
						</center></div>
						
			
		    {% endfor %}
		</div>
    	</ul>
	{% else %}
   	         <h3>You don't have any student</h3>
	{% endif %}
{% endblock %}

student/templates/student/login.html
{% extends 'student/base.html' %}
{% block title %}Login Student{% endblock %}


{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
                                     <h3>Add your details</h3>
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'student/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

student/templates/student/registration_form.html
{% extends 'student/base.html' %}
{% block title %}RegisterStudent{% endblock %}


{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
                                     <h3>Add your details</h3>
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'student/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

student/templates/student/student_form.html
{% extends 'student/base.html' %}
{% block title %}Edit your Details{% endblock %}
{% block albums_active  %}active{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'student/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

student/templates/student/studentcreate.html
<html>
<head>
	<title>{% block title %}Student Profile Portal{% endblock %}</title>
	{% load staticfiles %}

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
	<link rel="stylesheet" type="text/css" href="{% static 'student/style.css' %}" />

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
			 <span class="icon-bar"></span>
			 <span class="icon-bar"></span>
			 <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="{% url 'student:index' %}">Portal</a>
	</div>
	
    <!-- items -->
	<div class="collapse navbar-collapse" id="topNavBar">
		
		<ul class="nav navbar-nav">
			<li class="active">
				<a href="{% url 'student:index' %}">	
					<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
					Students
				</a>
			</li>
			
		</ul>

		<form class="navbar-form navbar-left" role="search" method="get" action="#">
			<div class="form-group">
				<input type="text" class="form-control" name="q" value="">
			</div>
			<button type="submit" class="btn btn-default">Search</button>
		
		</form>

		<ul class="nav navbar-nav navbar-right">
			<li class="">
				<a href="{% url 'student:studentcreate' %}">	
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
					Add your details
				</a>
			</li>
			<li class="">
				<a href="#">	
					<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
					Logout
				</a>
			</li>
		</ul>

	</div>
    </div>
</nav>
<h3>user = {{request.user.username}}</h3>
{% block body %}
{% endblock %}

</body>
</html>